version: "3.8"

services:
  psql-db:
    image: postgres
    container_name: psql-db
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'

  manage-airports:
    container_name: manage-airports-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    env_file:
      - .env
    depends_on:
      - psql-db
