version: "3.8"

services:
  psql-db:
    image: postgres
    restart: on-failure
    env_file:
      - .env
    ports:
      - '5432:5432'

  manage-airports:
    build: .
    image: airports:latest
    ports:
      - '9090:8080'
    env_file:
      - .env
    depends_on:
      - psql-db
    restart: on-failure
