apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-map
  namespace: devops-project
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: devops-project-postgres-secret
  namespace: devops-project
type: Opaque
data:
  password: cG9zdGdyZXM=

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: devops-project-postgres-pvc
  namespace: devops-project
  labels:
    app: postgres
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: devops-project-postgres
  namespace: devops-project
spec:
  serviceName: devops-project-postgres-service
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
        namespace: devops-project
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config-map
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: devops-project-postgres-secret
                  key: password

          volumeMounts:
            - name: devops-project-postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: devops-project-postgres-data
          persistentVolumeClaim:
            claimName: devops-project-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: devops-project-postgres-service
  namespace: devops-project
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432